language : node_js 
node_js:
    - "7.4.0"
services :
    - mysql
before_script :
    - npm install -g gulp-cli
    - npm install
    - gulp create-populate-db-test
before_install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS procare_db_test;'
script : gulp unit-test
after_script: gulp coveralls




