language : node_js 
services :
    - mysql
before_script :
    - npm install -g gulp-cli
    - npm install
before_install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS procare_db2;'
script : gulp test



